# Generated by Django 5.1.3 on 2024-11-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_branch_user_delivery_employee_menu_orders_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
